/* eslint-disable */
// AUTO-GENERATED by solid-jotl — do not edit.
import { createSignal } from 'solid-js'

/**
 * @typedef {Object} CounterProps
 *
 * initial?: number
 */
/** @param {CounterProps} props */
export function Counter(props) {

  const [count, setCount] = createSignal(props.initial ?? 0)

  function increment() {
    setCount(count() + 1)
  }

  function reset() {
    setCount(props.initial ?? 0)
  }
  return (
    <>
      <h1>
        Counter
      </h1>
      <p>
        Clicks: {count()}
      </p>
      <div class="jotl-group">
        <button onClick={increment}>
          Add
        </button>
        <button onClick={reset}>
          Reset
        </button>
      </div>
    </>
  )
}

export default Counter
