/* eslint-disable */
// AUTO-GENERATED by solid-jotl — do not edit.
import { createSignal } from 'solid-js'


const [totalClicks, setTotalClicks] = createSignal(0)

export function Counter() {

  const [count, setCount] = createSignal(0)
  function tap() {
    setCount(count() + 1)
    setTotalClicks(totalClicks() + 1)
  }
  return (
    <>
      <p>
        Local: {count()}
      </p>
      <button onClick={tap}>
        Tap
      </button>
    </>
  )
}

export function Stats() {
  return (
    <p>
      Total: {totalClicks()}
    </p>
  )
}

export default Counter
