/* eslint-disable */
// AUTO-GENERATED by solid-jotl — do not edit.
import { createSignal, Switch, Match, For } from 'solid-js'

export function Todos() {

  const [items, setItems] = createSignal(["apples", "bread"])
  const [showAll, setShowAll] = createSignal(true)
  return (
    <>
      <Switch>
        <Match when={showAll()}>
          <h2>
            All items
          </h2>
        </Match>
        <Match when={true}>
          <h2>
            Hidden
          </h2>
        </Match>
      </Switch>
      <ul>
        <For each={items()}>{(item) => (
          <li>
            {item}
          </li>
        )}</For>
      </ul>
    </>
  )
}

export default Todos
