/* eslint-disable */
// AUTO-GENERATED by solid-jotl — do not edit.
import { createSignal } from 'solid-js'


const [name, setName] = createSignal("world")
function greet() {
  setName("JOTL")
}

export function Default() {
  return (
    <>
      <h1>
        Hello, {name()}!
      </h1>
      <button onClick={greet}>
        Greet
      </button>
    </>
  )
}

export default Default
