/* eslint-disable */
// AUTO-GENERATED by solid-jotlang — do not edit.
import { MetaProvider as __JotlMetaProvider, Title as __JotlTitle, Meta as __JotlMeta, Link as __JotlLink } from 'solid-meta'

export function Default() {
  return (
    <__JotlMetaProvider>
      <__JotlTitle>Counter App</__JotlTitle>
      <__JotlMeta name="description" content="A tiny demo of solid-jotlang" />
      <__JotlMeta charset="utf-8" />
      <__JotlMeta name="viewport" content="width=device-width, initial-scale=1" />
      <__JotlMeta property="og:title" content="Counter" />
      <__JotlMeta name="twitter:card" content="summary" />
      <__JotlLink rel="canonical" href="https://example.com/counter" />
      <>
        <h1>
          Counter
        </h1>
        <p>
          Hello, world.
        </p>
      </>
    </__JotlMetaProvider>
  )
}

export default Default
